name = "MyObservables"
uuid = "df3871b9-5d65-4b03-8ddc-656e790b2c55"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]

[weakdeps]
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"

[extensions]
ObservablesExt = "Observables"
